#!/bin/bash -e

cd $(dirname $0)/..
source ./auto/set-env-helpers

kustomize edit set image joidevops/app=${ALICR_PREFIX}/${REPO_NAMESPACE}/${APP_NAME}:${GIT_HASH} joidevops/migration=${ALICR_PREFIX}/${REPO_NAMESPACE}/${MIGRATION_NAME}:${GIT_HASH} 

kustomize build . -o kustomize-output.yaml
