#!/bin/bash -e
set -x

export REPO_NAMESPACE="joidevops"
export APP_NAME="app"
export MIGRATION_NAME="migration"
export GIT_HASH=$(git rev-parse --short HEAD)
export TAG_TIME=$(date +'%Y%m%d%H%M')
PROJECT_NAME=${PROJECT_NAME:-joi}
KUBE_CONFILE="./config/kube-config.txt"
#ALICR_PREFIX="registry.cn-hongkong.aliyuncs.com"
export ALICR_PREFIX="k8s.test.io:30002/library"
PWD="D:\\cygwin64\\home\\Gene\\interview-test"

display_status() {
  echo ">>> $1 <<<" 1>&2
}

function terraform() {

  [[ ! -f ${CONF_DIR}/tmp/.env ]] && echo > ${CONF_DIR}/tmp/.env

  docker run --rm \
  -v ${PWD}:/working \
  -w /working \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  -e AWS_DEFAULT_REGION \
  --env-file ${CONF_DIR}/tmp/.env \
  hashicorp/terraform $@
}

function kubectl() {
  docker run --rm \
  -v ${PWD}/${KUBE_CONFILE}:/.kube/config \
  -v ${PWD}:/working \
  -w /working \
  bitnami/kubectl $@
}

function kustomize() {
  docker run --rm \
  -v ${PWD}/k8s:/working \
  -w /working \
  bitlayer/kustomize:v2.1.0 $@
}
